#!/bin/bash
VERSION="1.1.9"

LIGHT_GREEN='\033[1;32m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Load config file to get filepath
if [ -f  "dave.conf" ]
then
	source dave.conf
else
    filepath="dave.csv"
    echo "#!/bin/bash" > dave.conf
    echo "filepath='$filepath'" >> dave.conf
fi

# Create file if doesn't exist
touch filepath

if [ -z "$1" ]
then
	echo "No arguments. Refer to 'dave help' for options."
	exit 1
else
	command="$1"
fi

if [ $command = "tellme" ] || [ $command = "t" ]
then

	if [ -z "$2" ]
	then
		echo "Please specify which tag you would like to retrieve snippets for as the second argument. Refer to 'dave help' for options."
		exit 1
	else
		tag="$2"
	fi
	
	echo -e "\nSnippets for ${BLUE}$tag${NC}:"
	while IFS=, read -r col1 col2 col3
	do

		if [ -z "$col1" ]
		then
			# Tag is empty. It may be due to a malformatted csv file. Skipping this cycle of the loop.
			continue
		fi

		if [ "$col1" = "$tag" ]
		then 
			# Found a match.
	    	echo -e "   ${BLUE}$col2${NC}\t$col3"
	    fi
	done < $filepath

	# Jump to a new line
	echo -e "" 
	
elif [ $command = "remember" ] || [ $command = "r" ]
then

	if [ -z "$2" ]
	then
	  	# No tag provided. Launch a prompt to ask for it.
	    read -p "Tag: " tag 
	else
	  	tag="$2"
	fi

	if [ -z "$3" ]	
	then
	    # No snippet provided. Launch a prompt to ask for it.
		read -p "Snippet: " newsnippet 
	else
		newsnippet="$3"
	fi
		
	if [ -z "$4" ]
	then
	    # No description provided. Launch a prompt to ask for it.
	    read -p "Description: " description 
    else
	  	description="$4"
	fi

    # Append to file. 
	echo $tag,$newsnippet,$description >> $filepath

	# Check for commas in the texts and replace them with space, so they won't corrupt the csv file.
	tag=${tag//,/ }
	newsnippet=${newsnippet//,/ }
	description=${description//,/ }
	
	# Print out the saved content
	echo -e "${GREEN}For tag:${NC} $tag ${GREEN}added snippet:${NC} $newsnippet ${GREEN}with the description:${NC} $description"

elif [ $command = "show" ] || [ $command = "s" ]
then
	open dave.csv
elif [ $command = "help" ] || [ $command = "h" ] || [ $command = "--help" ] || [ $command = "-h" ]
	then
	echo -e "┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐\
	       \n│ Tell me what the snippets are for a tag:  ${BLUE}'dave tellme [tag]'${NC} or ${BLUE}'dave t [tag]'${NC}                                                   |\
	       \n│ Remember (i.e. save) a snippet for later: ${BLUE}'dave remember [tag] [snippet] [description]'${NC} or ${BLUE}'dave r [tag] [snippet] [description]'${NC} |\
	       \n│ Show all snippets as a csv file:          ${BLUE}'dave show'${NC} or ${BLUE}'dave s'${NC}                                                                 │\
	       \n│ Get the current version of this tool:     ${BLUE}'dave version'${NC} or ${BLUE}'dave v'${NC}                                                              │\
	       \n│ Bring up this help info:                  ${BLUE}'dave help'${NC} or ${BLUE}'dave h'${NC}                                                                 │\
	       \n└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘"
elif [ $command = "version" ] || [ $command = "v" ] || [ $command = "--version" ] || [ $command = "-v" ]
then
	echo "Smart-snippets version: $VERSION"
else
	echo -e "${RED}I don't understand: $command${NC}\nRefer to 'dave --help' for options."
fi
